// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqdUkQLcozYH9I46vjm9pbL3IXzIM264M',
    appId: '1:416840793071:web:7308a1d13812e6f01b141a',
    messagingSenderId: '416840793071',
    projectId: 'feedforward-91744',
    authDomain: 'feedforward-91744.firebaseapp.com',
    storageBucket: 'feedforward-91744.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmtNKJ7JqUJBioRTyd43S677q4gTybg1c',
    appId: '1:416840793071:android:98f90d01679919001b141a',
    messagingSenderId: '416840793071',
    projectId: 'feedforward-91744',
    storageBucket: 'feedforward-91744.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-TU6n_Sn9mrHd3eA9Y3Nk8NxAvfKJOxk',
    appId: '1:416840793071:ios:e03275f5cc51eda11b141a',
    messagingSenderId: '416840793071',
    projectId: 'feedforward-91744',
    storageBucket: 'feedforward-91744.appspot.com',
    iosBundleId: 'com.example.fbmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-TU6n_Sn9mrHd3eA9Y3Nk8NxAvfKJOxk',
    appId: '1:416840793071:ios:e03275f5cc51eda11b141a',
    messagingSenderId: '416840793071',
    projectId: 'feedforward-91744',
    storageBucket: 'feedforward-91744.appspot.com',
    iosBundleId: 'com.example.fbmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqdUkQLcozYH9I46vjm9pbL3IXzIM264M',
    appId: '1:416840793071:web:4d8a1170c5a7b6331b141a',
    messagingSenderId: '416840793071',
    projectId: 'feedforward-91744',
    authDomain: 'feedforward-91744.firebaseapp.com',
    storageBucket: 'feedforward-91744.appspot.com',
  );
}
